name: Publish on Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and Publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v1
      - name: Build docker images
        run: make docker DOCKER_REGISTRY=docker.pkg.github.com DOCKER_CONTEXT_PATH=xmlking/micro-starter-kit
      - name: Push docker images
        run: |
          # docker login docker.pkg.github.com -u $GITHUB_ACTOR -p  ${{ secrets.GITHUB_TOKEN }}
          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_DOCKER_PASSWORD }}
          make docker_push
